# Generated by Django 4.2.5 on 2023-09-06 19:11

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("hospitales", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Servicio",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                (
                    "uuid",
                    models.UUIDField(default=uuid.uuid4, editable=False, null=True),
                ),
                ("status", models.SmallIntegerField(default=1)),
                ("active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True, null=True)),
                ("updated_at", models.DateTimeField(auto_now=True, null=True)),
                ("nombre", models.CharField(max_length=15)),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="HospitalServicio",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                (
                    "uuid",
                    models.UUIDField(default=uuid.uuid4, editable=False, null=True),
                ),
                ("status", models.SmallIntegerField(default=1)),
                ("active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True, null=True)),
                ("updated_at", models.DateTimeField(auto_now=True, null=True)),
                (
                    "hospital",
                    models.ForeignKey(
                        db_column="hospital_id",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="hospitales.hospital",
                    ),
                ),
                (
                    "servicio",
                    models.ForeignKey(
                        db_column="servicio_id",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="servicios.servicio",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
