# Generated by Django 4.1.6 on 2023-09-06 17:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("hospitales", "0001_initial"),
    ]

    operations = [
        migrations.DeleteModel(
            name="HospitalServicio",
        ),
        migrations.DeleteModel(
            name="Servicio",
        ),
    ]
