# Generated by Django 4.2.5 on 2023-09-07 07:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("hospitales", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="hospital",
            name="clave_entidad",
            field=models.SmallIntegerField(null=True),
        ),
    ]
