# Generated by Django 4.2.5 on 2023-09-07 06:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("pacientes", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="paciente",
            name="mac_tarjeta",
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AddField(
            model_name="paciente",
            name="tiene_tarjeta",
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name="PacienteTarjeta",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("mac_tarjeta", models.CharField(max_length=30, null=True)),
                ("motivo_baja", models.CharField(max_length=200, null=True)),
                (
                    "paciente",
                    models.ForeignKey(
                        db_column="paciente_id",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="pacientes.paciente",
                    ),
                ),
            ],
            options={
                "db_table": "tarjetas_paciente",
            },
        ),
    ]
