# Generated by Django 4.2.5 on 2023-09-07 15:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("pacientes", "0002_paciente_mac_tarjeta_paciente_tiene_tarjeta_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="paciente",
            old_name="a_isste",
            new_name="a_issste",
        ),
    ]
