# Generated by Django 4.2.5 on 2023-09-07 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pacientes", "0003_rename_a_isste_paciente_a_issste"),
    ]

    operations = [
        migrations.AddField(
            model_name="pacientetarjeta",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name="pacientetarjeta",
            name="updated_at",
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
