# Generated by Django 4.2.5 on 2023-09-06 23:14

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="TipoRegistro",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                (
                    "uuid",
                    models.UUIDField(default=uuid.uuid4, editable=False, null=True),
                ),
                ("status", models.SmallIntegerField(default=1)),
                ("active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True, null=True)),
                ("updated_at", models.DateTimeField(auto_now=True, null=True)),
                ("nombre", models.CharField(max_length=15)),
            ],
            options={
                "db_table": "tipos_registro",
            },
        ),
        migrations.CreateModel(
            name="Registro",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                (
                    "uuid",
                    models.UUIDField(default=uuid.uuid4, editable=False, null=True),
                ),
                ("status", models.SmallIntegerField(default=1)),
                ("active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True, null=True)),
                ("updated_at", models.DateTimeField(auto_now=True, null=True)),
                (
                    "tipo_registro",
                    models.ForeignKey(
                        db_column="tipo_registro_id",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="registros.tiporegistro",
                    ),
                ),
            ],
            options={
                "db_table": "registros",
            },
        ),
    ]
