# Generated by Django 4.2.5 on 2023-09-06 23:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("registros", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="tiporegistro",
            name="nombre",
            field=models.CharField(max_length=50),
        ),
    ]
