# Generated by Django 4.2.5 on 2023-09-06 23:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("registros", "0002_alter_tiporegistro_nombre"),
    ]

    operations = [
        migrations.AddField(
            model_name="registro",
            name="card",
            field=models.CharField(max_length=50, null=True),
        ),
    ]
